// Generated by gencpp from file behaviour/areareq.msg
// DO NOT EDIT!


#ifndef BEHAVIOUR_MESSAGE_AREAREQ_H
#define BEHAVIOUR_MESSAGE_AREAREQ_H

#include <ros/service_traits.h>


#include <behaviour/areareqRequest.h>
#include <behaviour/areareqResponse.h>


namespace behaviour
{

struct areareq
{

typedef areareqRequest Request;
typedef areareqResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct areareq
} // namespace behaviour


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::behaviour::areareq > {
  static const char* value()
  {
    return "a4a19e72d17da6e4ff5c0b9f7a7ca609";
  }

  static const char* value(const ::behaviour::areareq&) { return value(); }
};

template<>
struct DataType< ::behaviour::areareq > {
  static const char* value()
  {
    return "behaviour/areareq";
  }

  static const char* value(const ::behaviour::areareq&) { return value(); }
};


// service_traits::MD5Sum< ::behaviour::areareqRequest> should match
// service_traits::MD5Sum< ::behaviour::areareq >
template<>
struct MD5Sum< ::behaviour::areareqRequest>
{
  static const char* value()
  {
    return MD5Sum< ::behaviour::areareq >::value();
  }
  static const char* value(const ::behaviour::areareqRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::behaviour::areareqRequest> should match
// service_traits::DataType< ::behaviour::areareq >
template<>
struct DataType< ::behaviour::areareqRequest>
{
  static const char* value()
  {
    return DataType< ::behaviour::areareq >::value();
  }
  static const char* value(const ::behaviour::areareqRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::behaviour::areareqResponse> should match
// service_traits::MD5Sum< ::behaviour::areareq >
template<>
struct MD5Sum< ::behaviour::areareqResponse>
{
  static const char* value()
  {
    return MD5Sum< ::behaviour::areareq >::value();
  }
  static const char* value(const ::behaviour::areareqResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::behaviour::areareqResponse> should match
// service_traits::DataType< ::behaviour::areareq >
template<>
struct DataType< ::behaviour::areareqResponse>
{
  static const char* value()
  {
    return DataType< ::behaviour::areareq >::value();
  }
  static const char* value(const ::behaviour::areareqResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEHAVIOUR_MESSAGE_AREAREQ_H
