// Generated by gencpp from file behaviour/drone_hello.msg
// DO NOT EDIT!


#ifndef BEHAVIOUR_MESSAGE_DRONE_HELLO_H
#define BEHAVIOUR_MESSAGE_DRONE_HELLO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace behaviour
{
template <class ContainerAllocator>
struct drone_hello_
{
  typedef drone_hello_<ContainerAllocator> Type;

  drone_hello_()
    : header()
    , drone_id(0)
    , mode(0)
    , type(0)  {
    }
  drone_hello_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , drone_id(0)
    , mode(0)
    , type(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _drone_id_type;
  _drone_id_type drone_id;

   typedef int8_t _mode_type;
  _mode_type mode;

   typedef int8_t _type_type;
  _type_type type;





  typedef boost::shared_ptr< ::behaviour::drone_hello_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behaviour::drone_hello_<ContainerAllocator> const> ConstPtr;

}; // struct drone_hello_

typedef ::behaviour::drone_hello_<std::allocator<void> > drone_hello;

typedef boost::shared_ptr< ::behaviour::drone_hello > drone_helloPtr;
typedef boost::shared_ptr< ::behaviour::drone_hello const> drone_helloConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behaviour::drone_hello_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behaviour::drone_hello_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behaviour::drone_hello_<ContainerAllocator1> & lhs, const ::behaviour::drone_hello_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.drone_id == rhs.drone_id &&
    lhs.mode == rhs.mode &&
    lhs.type == rhs.type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behaviour::drone_hello_<ContainerAllocator1> & lhs, const ::behaviour::drone_hello_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behaviour

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::behaviour::drone_hello_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behaviour::drone_hello_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour::drone_hello_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour::drone_hello_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour::drone_hello_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour::drone_hello_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behaviour::drone_hello_<ContainerAllocator> >
{
  static const char* value()
  {
    return "806724bc17f1cf32390948a6a8836584";
  }

  static const char* value(const ::behaviour::drone_hello_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x806724bc17f1cf32ULL;
  static const uint64_t static_value2 = 0x390948a6a8836584ULL;
};

template<class ContainerAllocator>
struct DataType< ::behaviour::drone_hello_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behaviour/drone_hello";
  }

  static const char* value(const ::behaviour::drone_hello_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behaviour::drone_hello_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int8 drone_id\n"
"int8 mode\n"
"int8 type\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::behaviour::drone_hello_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behaviour::drone_hello_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.drone_id);
      stream.next(m.mode);
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct drone_hello_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behaviour::drone_hello_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behaviour::drone_hello_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "drone_id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.drone_id);
    s << indent << "mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "type: ";
    Printer<int8_t>::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOUR_MESSAGE_DRONE_HELLO_H
