// Generated by gencpp from file behaviour/drone_state.msg
// DO NOT EDIT!


#ifndef BEHAVIOUR_MESSAGE_DRONE_STATE_H
#define BEHAVIOUR_MESSAGE_DRONE_STATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <behaviour/drone_geometry.h>
#include <behaviour/score.h>
#include <behaviour/task.h>

namespace behaviour
{
template <class ContainerAllocator>
struct drone_state_
{
  typedef drone_state_<ContainerAllocator> Type;

  drone_state_()
    : header()
    , drone_id(0)
    , mode(0)
    , type(0)
    , messagetime(0.0)
    , drone_geometry()
    , battery(0)
    , drone_soh(0)
    , score()
    , task()  {
    }
  drone_state_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , drone_id(0)
    , mode(0)
    , type(0)
    , messagetime(0.0)
    , drone_geometry(_alloc)
    , battery(0)
    , drone_soh(0)
    , score(_alloc)
    , task(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _drone_id_type;
  _drone_id_type drone_id;

   typedef int8_t _mode_type;
  _mode_type mode;

   typedef int8_t _type_type;
  _type_type type;

   typedef double _messagetime_type;
  _messagetime_type messagetime;

   typedef  ::behaviour::drone_geometry_<ContainerAllocator>  _drone_geometry_type;
  _drone_geometry_type drone_geometry;

   typedef int8_t _battery_type;
  _battery_type battery;

   typedef int8_t _drone_soh_type;
  _drone_soh_type drone_soh;

   typedef  ::behaviour::score_<ContainerAllocator>  _score_type;
  _score_type score;

   typedef  ::behaviour::task_<ContainerAllocator>  _task_type;
  _task_type task;





  typedef boost::shared_ptr< ::behaviour::drone_state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behaviour::drone_state_<ContainerAllocator> const> ConstPtr;

}; // struct drone_state_

typedef ::behaviour::drone_state_<std::allocator<void> > drone_state;

typedef boost::shared_ptr< ::behaviour::drone_state > drone_statePtr;
typedef boost::shared_ptr< ::behaviour::drone_state const> drone_stateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behaviour::drone_state_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behaviour::drone_state_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behaviour::drone_state_<ContainerAllocator1> & lhs, const ::behaviour::drone_state_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.drone_id == rhs.drone_id &&
    lhs.mode == rhs.mode &&
    lhs.type == rhs.type &&
    lhs.messagetime == rhs.messagetime &&
    lhs.drone_geometry == rhs.drone_geometry &&
    lhs.battery == rhs.battery &&
    lhs.drone_soh == rhs.drone_soh &&
    lhs.score == rhs.score &&
    lhs.task == rhs.task;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behaviour::drone_state_<ContainerAllocator1> & lhs, const ::behaviour::drone_state_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behaviour

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::behaviour::drone_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behaviour::drone_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour::drone_state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour::drone_state_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour::drone_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour::drone_state_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behaviour::drone_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5309d0e3c8a877ad2b981cbca29cefc4";
  }

  static const char* value(const ::behaviour::drone_state_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5309d0e3c8a877adULL;
  static const uint64_t static_value2 = 0x2b981cbca29cefc4ULL;
};

template<class ContainerAllocator>
struct DataType< ::behaviour::drone_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behaviour/drone_state";
  }

  static const char* value(const ::behaviour::drone_state_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behaviour::drone_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int8 drone_id\n"
"int8 mode\n"
"int8 type\n"
"float64 messagetime\n"
"drone_geometry drone_geometry\n"
"int8 battery\n"
"int8 drone_soh\n"
"score score\n"
"task task\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: behaviour/drone_geometry\n"
"Header header\n"
"float64 lat\n"
"float64 lon\n"
"float32 alt\n"
"float32 yaw\n"
"float32 roll\n"
"float32 pitch\n"
"================================================================================\n"
"MSG: behaviour/score\n"
"Header header\n"
"int8 drone_id\n"
"int8 task_id\n"
"float32 score\n"
"\n"
"================================================================================\n"
"MSG: behaviour/task\n"
"Header header\n"
"int8 task_id\n"
"task_geometry task_geometry\n"
"int8 allocated\n"
"int8 type\n"
"\n"
"================================================================================\n"
"MSG: behaviour/task_geometry\n"
"Header header\n"
"float64 lat\n"
"float64 lon\n"
"float32 alt\n"
;
  }

  static const char* value(const ::behaviour::drone_state_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behaviour::drone_state_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.drone_id);
      stream.next(m.mode);
      stream.next(m.type);
      stream.next(m.messagetime);
      stream.next(m.drone_geometry);
      stream.next(m.battery);
      stream.next(m.drone_soh);
      stream.next(m.score);
      stream.next(m.task);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct drone_state_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behaviour::drone_state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behaviour::drone_state_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "drone_id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.drone_id);
    s << indent << "mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "type: ";
    Printer<int8_t>::stream(s, indent + "  ", v.type);
    s << indent << "messagetime: ";
    Printer<double>::stream(s, indent + "  ", v.messagetime);
    s << indent << "drone_geometry: ";
    s << std::endl;
    Printer< ::behaviour::drone_geometry_<ContainerAllocator> >::stream(s, indent + "  ", v.drone_geometry);
    s << indent << "battery: ";
    Printer<int8_t>::stream(s, indent + "  ", v.battery);
    s << indent << "drone_soh: ";
    Printer<int8_t>::stream(s, indent + "  ", v.drone_soh);
    s << indent << "score: ";
    s << std::endl;
    Printer< ::behaviour::score_<ContainerAllocator> >::stream(s, indent + "  ", v.score);
    s << indent << "task: ";
    s << std::endl;
    Printer< ::behaviour::task_<ContainerAllocator> >::stream(s, indent + "  ", v.task);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOUR_MESSAGE_DRONE_STATE_H
