// Generated by gencpp from file behaviour/drone_geometry.msg
// DO NOT EDIT!


#ifndef BEHAVIOUR_MESSAGE_DRONE_GEOMETRY_H
#define BEHAVIOUR_MESSAGE_DRONE_GEOMETRY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace behaviour
{
template <class ContainerAllocator>
struct drone_geometry_
{
  typedef drone_geometry_<ContainerAllocator> Type;

  drone_geometry_()
    : header()
    , lat(0.0)
    , lon(0.0)
    , alt(0.0)
    , yaw(0.0)
    , roll(0.0)
    , pitch(0.0)  {
    }
  drone_geometry_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , lat(0.0)
    , lon(0.0)
    , alt(0.0)
    , yaw(0.0)
    , roll(0.0)
    , pitch(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _lat_type;
  _lat_type lat;

   typedef double _lon_type;
  _lon_type lon;

   typedef float _alt_type;
  _alt_type alt;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;





  typedef boost::shared_ptr< ::behaviour::drone_geometry_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behaviour::drone_geometry_<ContainerAllocator> const> ConstPtr;

}; // struct drone_geometry_

typedef ::behaviour::drone_geometry_<std::allocator<void> > drone_geometry;

typedef boost::shared_ptr< ::behaviour::drone_geometry > drone_geometryPtr;
typedef boost::shared_ptr< ::behaviour::drone_geometry const> drone_geometryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behaviour::drone_geometry_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behaviour::drone_geometry_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behaviour::drone_geometry_<ContainerAllocator1> & lhs, const ::behaviour::drone_geometry_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.lat == rhs.lat &&
    lhs.lon == rhs.lon &&
    lhs.alt == rhs.alt &&
    lhs.yaw == rhs.yaw &&
    lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behaviour::drone_geometry_<ContainerAllocator1> & lhs, const ::behaviour::drone_geometry_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behaviour

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::behaviour::drone_geometry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behaviour::drone_geometry_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour::drone_geometry_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour::drone_geometry_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour::drone_geometry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour::drone_geometry_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behaviour::drone_geometry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c58ba677212f5ce7784c765ca6849f24";
  }

  static const char* value(const ::behaviour::drone_geometry_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc58ba677212f5ce7ULL;
  static const uint64_t static_value2 = 0x784c765ca6849f24ULL;
};

template<class ContainerAllocator>
struct DataType< ::behaviour::drone_geometry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behaviour/drone_geometry";
  }

  static const char* value(const ::behaviour::drone_geometry_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behaviour::drone_geometry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 lat\n"
"float64 lon\n"
"float32 alt\n"
"float32 yaw\n"
"float32 roll\n"
"float32 pitch\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::behaviour::drone_geometry_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behaviour::drone_geometry_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.lat);
      stream.next(m.lon);
      stream.next(m.alt);
      stream.next(m.yaw);
      stream.next(m.roll);
      stream.next(m.pitch);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct drone_geometry_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behaviour::drone_geometry_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behaviour::drone_geometry_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "lat: ";
    Printer<double>::stream(s, indent + "  ", v.lat);
    s << indent << "lon: ";
    Printer<double>::stream(s, indent + "  ", v.lon);
    s << indent << "alt: ";
    Printer<float>::stream(s, indent + "  ", v.alt);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOUR_MESSAGE_DRONE_GEOMETRY_H
