// Generated by gencpp from file behaviour/members.msg
// DO NOT EDIT!


#ifndef BEHAVIOUR_MESSAGE_MEMBERS_H
#define BEHAVIOUR_MESSAGE_MEMBERS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <behaviour/drone_state.h>

namespace behaviour
{
template <class ContainerAllocator>
struct members_
{
  typedef members_<ContainerAllocator> Type;

  members_()
    : header()
    , drone_states()  {
    }
  members_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , drone_states(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::behaviour::drone_state_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::behaviour::drone_state_<ContainerAllocator> >::other >  _drone_states_type;
  _drone_states_type drone_states;





  typedef boost::shared_ptr< ::behaviour::members_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behaviour::members_<ContainerAllocator> const> ConstPtr;

}; // struct members_

typedef ::behaviour::members_<std::allocator<void> > members;

typedef boost::shared_ptr< ::behaviour::members > membersPtr;
typedef boost::shared_ptr< ::behaviour::members const> membersConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behaviour::members_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behaviour::members_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behaviour::members_<ContainerAllocator1> & lhs, const ::behaviour::members_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.drone_states == rhs.drone_states;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behaviour::members_<ContainerAllocator1> & lhs, const ::behaviour::members_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behaviour

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::behaviour::members_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behaviour::members_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour::members_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour::members_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour::members_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour::members_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behaviour::members_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d2196bf9ce28bd860ccf7a719e388ff5";
  }

  static const char* value(const ::behaviour::members_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd2196bf9ce28bd86ULL;
  static const uint64_t static_value2 = 0x0ccf7a719e388ff5ULL;
};

template<class ContainerAllocator>
struct DataType< ::behaviour::members_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behaviour/members";
  }

  static const char* value(const ::behaviour::members_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behaviour::members_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"drone_state[] drone_states\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: behaviour/drone_state\n"
"Header header\n"
"int8 drone_id\n"
"int8 mode\n"
"int8 type\n"
"float64 messagetime\n"
"drone_geometry drone_geometry\n"
"int8 battery\n"
"int8 drone_soh\n"
"score score\n"
"task task\n"
"================================================================================\n"
"MSG: behaviour/drone_geometry\n"
"Header header\n"
"float64 lat\n"
"float64 lon\n"
"float32 alt\n"
"float32 yaw\n"
"float32 roll\n"
"float32 pitch\n"
"================================================================================\n"
"MSG: behaviour/score\n"
"Header header\n"
"int8 drone_id\n"
"int8 task_id\n"
"float32 score\n"
"\n"
"================================================================================\n"
"MSG: behaviour/task\n"
"Header header\n"
"int8 task_id\n"
"task_geometry task_geometry\n"
"int8 allocated\n"
"int8 type\n"
"\n"
"================================================================================\n"
"MSG: behaviour/task_geometry\n"
"Header header\n"
"float64 lat\n"
"float64 lon\n"
"float32 alt\n"
;
  }

  static const char* value(const ::behaviour::members_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behaviour::members_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.drone_states);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct members_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behaviour::members_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behaviour::members_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "drone_states[]" << std::endl;
    for (size_t i = 0; i < v.drone_states.size(); ++i)
    {
      s << indent << "  drone_states[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::behaviour::drone_state_<ContainerAllocator> >::stream(s, indent + "    ", v.drone_states[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOUR_MESSAGE_MEMBERS_H
