// Generated by gencpp from file behaviour/swarmstate.msg
// DO NOT EDIT!


#ifndef BEHAVIOUR_MESSAGE_SWARMSTATE_H
#define BEHAVIOUR_MESSAGE_SWARMSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace behaviour
{
template <class ContainerAllocator>
struct swarmstate_
{
  typedef swarmstate_<ContainerAllocator> Type;

  swarmstate_()
    : num_mon(0)
    , num_track(0)
    , available_track(0)  {
    }
  swarmstate_(const ContainerAllocator& _alloc)
    : num_mon(0)
    , num_track(0)
    , available_track(0)  {
  (void)_alloc;
    }



   typedef int8_t _num_mon_type;
  _num_mon_type num_mon;

   typedef int8_t _num_track_type;
  _num_track_type num_track;

   typedef int8_t _available_track_type;
  _available_track_type available_track;





  typedef boost::shared_ptr< ::behaviour::swarmstate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behaviour::swarmstate_<ContainerAllocator> const> ConstPtr;

}; // struct swarmstate_

typedef ::behaviour::swarmstate_<std::allocator<void> > swarmstate;

typedef boost::shared_ptr< ::behaviour::swarmstate > swarmstatePtr;
typedef boost::shared_ptr< ::behaviour::swarmstate const> swarmstateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behaviour::swarmstate_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behaviour::swarmstate_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behaviour::swarmstate_<ContainerAllocator1> & lhs, const ::behaviour::swarmstate_<ContainerAllocator2> & rhs)
{
  return lhs.num_mon == rhs.num_mon &&
    lhs.num_track == rhs.num_track &&
    lhs.available_track == rhs.available_track;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behaviour::swarmstate_<ContainerAllocator1> & lhs, const ::behaviour::swarmstate_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behaviour

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::behaviour::swarmstate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behaviour::swarmstate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour::swarmstate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour::swarmstate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour::swarmstate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour::swarmstate_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behaviour::swarmstate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a525631f8ad4b69497b0091550a7555c";
  }

  static const char* value(const ::behaviour::swarmstate_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa525631f8ad4b694ULL;
  static const uint64_t static_value2 = 0x97b0091550a7555cULL;
};

template<class ContainerAllocator>
struct DataType< ::behaviour::swarmstate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behaviour/swarmstate";
  }

  static const char* value(const ::behaviour::swarmstate_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behaviour::swarmstate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 num_mon\n"
"int8 num_track\n"
"int8 available_track\n"
;
  }

  static const char* value(const ::behaviour::swarmstate_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behaviour::swarmstate_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num_mon);
      stream.next(m.num_track);
      stream.next(m.available_track);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct swarmstate_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behaviour::swarmstate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behaviour::swarmstate_<ContainerAllocator>& v)
  {
    s << indent << "num_mon: ";
    Printer<int8_t>::stream(s, indent + "  ", v.num_mon);
    s << indent << "num_track: ";
    Printer<int8_t>::stream(s, indent + "  ", v.num_track);
    s << indent << "available_track: ";
    Printer<int8_t>::stream(s, indent + "  ", v.available_track);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOUR_MESSAGE_SWARMSTATE_H
