// Generated by gencpp from file behaviour/swarmstatereqRESPONSERequest.msg
// DO NOT EDIT!


#ifndef BEHAVIOUR_MESSAGE_SWARMSTATEREQRESPONSEREQUEST_H
#define BEHAVIOUR_MESSAGE_SWARMSTATEREQRESPONSEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace behaviour
{
template <class ContainerAllocator>
struct swarmstatereqRESPONSERequest_
{
  typedef swarmstatereqRESPONSERequest_<ContainerAllocator> Type;

  swarmstatereqRESPONSERequest_()
    : a(0)  {
    }
  swarmstatereqRESPONSERequest_(const ContainerAllocator& _alloc)
    : a(0)  {
  (void)_alloc;
    }



   typedef int8_t _a_type;
  _a_type a;





  typedef boost::shared_ptr< ::behaviour::swarmstatereqRESPONSERequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behaviour::swarmstatereqRESPONSERequest_<ContainerAllocator> const> ConstPtr;

}; // struct swarmstatereqRESPONSERequest_

typedef ::behaviour::swarmstatereqRESPONSERequest_<std::allocator<void> > swarmstatereqRESPONSERequest;

typedef boost::shared_ptr< ::behaviour::swarmstatereqRESPONSERequest > swarmstatereqRESPONSERequestPtr;
typedef boost::shared_ptr< ::behaviour::swarmstatereqRESPONSERequest const> swarmstatereqRESPONSERequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behaviour::swarmstatereqRESPONSERequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behaviour::swarmstatereqRESPONSERequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behaviour::swarmstatereqRESPONSERequest_<ContainerAllocator1> & lhs, const ::behaviour::swarmstatereqRESPONSERequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behaviour::swarmstatereqRESPONSERequest_<ContainerAllocator1> & lhs, const ::behaviour::swarmstatereqRESPONSERequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behaviour

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::behaviour::swarmstatereqRESPONSERequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behaviour::swarmstatereqRESPONSERequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour::swarmstatereqRESPONSERequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour::swarmstatereqRESPONSERequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour::swarmstatereqRESPONSERequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour::swarmstatereqRESPONSERequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behaviour::swarmstatereqRESPONSERequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4eec2979cc688371cc0e7f01aea37ad1";
  }

  static const char* value(const ::behaviour::swarmstatereqRESPONSERequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4eec2979cc688371ULL;
  static const uint64_t static_value2 = 0xcc0e7f01aea37ad1ULL;
};

template<class ContainerAllocator>
struct DataType< ::behaviour::swarmstatereqRESPONSERequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behaviour/swarmstatereqRESPONSERequest";
  }

  static const char* value(const ::behaviour::swarmstatereqRESPONSERequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behaviour::swarmstatereqRESPONSERequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 a\n"
;
  }

  static const char* value(const ::behaviour::swarmstatereqRESPONSERequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behaviour::swarmstatereqRESPONSERequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct swarmstatereqRESPONSERequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behaviour::swarmstatereqRESPONSERequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behaviour::swarmstatereqRESPONSERequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int8_t>::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOUR_MESSAGE_SWARMSTATEREQRESPONSEREQUEST_H
