// Generated by gencpp from file behaviour/swarmstatereqRESPONSEResponse.msg
// DO NOT EDIT!


#ifndef BEHAVIOUR_MESSAGE_SWARMSTATEREQRESPONSERESPONSE_H
#define BEHAVIOUR_MESSAGE_SWARMSTATEREQRESPONSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <behaviour/swarmstate.h>

namespace behaviour
{
template <class ContainerAllocator>
struct swarmstatereqRESPONSEResponse_
{
  typedef swarmstatereqRESPONSEResponse_<ContainerAllocator> Type;

  swarmstatereqRESPONSEResponse_()
    : swarmstate()  {
    }
  swarmstatereqRESPONSEResponse_(const ContainerAllocator& _alloc)
    : swarmstate(_alloc)  {
  (void)_alloc;
    }



   typedef  ::behaviour::swarmstate_<ContainerAllocator>  _swarmstate_type;
  _swarmstate_type swarmstate;





  typedef boost::shared_ptr< ::behaviour::swarmstatereqRESPONSEResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behaviour::swarmstatereqRESPONSEResponse_<ContainerAllocator> const> ConstPtr;

}; // struct swarmstatereqRESPONSEResponse_

typedef ::behaviour::swarmstatereqRESPONSEResponse_<std::allocator<void> > swarmstatereqRESPONSEResponse;

typedef boost::shared_ptr< ::behaviour::swarmstatereqRESPONSEResponse > swarmstatereqRESPONSEResponsePtr;
typedef boost::shared_ptr< ::behaviour::swarmstatereqRESPONSEResponse const> swarmstatereqRESPONSEResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behaviour::swarmstatereqRESPONSEResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behaviour::swarmstatereqRESPONSEResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behaviour::swarmstatereqRESPONSEResponse_<ContainerAllocator1> & lhs, const ::behaviour::swarmstatereqRESPONSEResponse_<ContainerAllocator2> & rhs)
{
  return lhs.swarmstate == rhs.swarmstate;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behaviour::swarmstatereqRESPONSEResponse_<ContainerAllocator1> & lhs, const ::behaviour::swarmstatereqRESPONSEResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behaviour

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::behaviour::swarmstatereqRESPONSEResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behaviour::swarmstatereqRESPONSEResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour::swarmstatereqRESPONSEResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour::swarmstatereqRESPONSEResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour::swarmstatereqRESPONSEResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour::swarmstatereqRESPONSEResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behaviour::swarmstatereqRESPONSEResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "67bfcb736767ba918516cbb9ae24522d";
  }

  static const char* value(const ::behaviour::swarmstatereqRESPONSEResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x67bfcb736767ba91ULL;
  static const uint64_t static_value2 = 0x8516cbb9ae24522dULL;
};

template<class ContainerAllocator>
struct DataType< ::behaviour::swarmstatereqRESPONSEResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behaviour/swarmstatereqRESPONSEResponse";
  }

  static const char* value(const ::behaviour::swarmstatereqRESPONSEResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behaviour::swarmstatereqRESPONSEResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarmstate swarmstate\n"
"\n"
"================================================================================\n"
"MSG: behaviour/swarmstate\n"
"int8 num_mon\n"
"int8 num_track\n"
"int8 available_track\n"
;
  }

  static const char* value(const ::behaviour::swarmstatereqRESPONSEResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behaviour::swarmstatereqRESPONSEResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.swarmstate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct swarmstatereqRESPONSEResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behaviour::swarmstatereqRESPONSEResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behaviour::swarmstatereqRESPONSEResponse_<ContainerAllocator>& v)
  {
    s << indent << "swarmstate: ";
    s << std::endl;
    Printer< ::behaviour::swarmstate_<ContainerAllocator> >::stream(s, indent + "  ", v.swarmstate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOUR_MESSAGE_SWARMSTATEREQRESPONSERESPONSE_H
