// Generated by gencpp from file behaviour/swarmstatereqRequest.msg
// DO NOT EDIT!


#ifndef BEHAVIOUR_MESSAGE_SWARMSTATEREQREQUEST_H
#define BEHAVIOUR_MESSAGE_SWARMSTATEREQREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace behaviour
{
template <class ContainerAllocator>
struct swarmstatereqRequest_
{
  typedef swarmstatereqRequest_<ContainerAllocator> Type;

  swarmstatereqRequest_()
    : pass(0)  {
    }
  swarmstatereqRequest_(const ContainerAllocator& _alloc)
    : pass(0)  {
  (void)_alloc;
    }



   typedef int8_t _pass_type;
  _pass_type pass;





  typedef boost::shared_ptr< ::behaviour::swarmstatereqRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behaviour::swarmstatereqRequest_<ContainerAllocator> const> ConstPtr;

}; // struct swarmstatereqRequest_

typedef ::behaviour::swarmstatereqRequest_<std::allocator<void> > swarmstatereqRequest;

typedef boost::shared_ptr< ::behaviour::swarmstatereqRequest > swarmstatereqRequestPtr;
typedef boost::shared_ptr< ::behaviour::swarmstatereqRequest const> swarmstatereqRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behaviour::swarmstatereqRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behaviour::swarmstatereqRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behaviour::swarmstatereqRequest_<ContainerAllocator1> & lhs, const ::behaviour::swarmstatereqRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pass == rhs.pass;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behaviour::swarmstatereqRequest_<ContainerAllocator1> & lhs, const ::behaviour::swarmstatereqRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behaviour

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::behaviour::swarmstatereqRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behaviour::swarmstatereqRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour::swarmstatereqRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour::swarmstatereqRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour::swarmstatereqRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour::swarmstatereqRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behaviour::swarmstatereqRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e370fd289e7d098aaf730ef08ac3ee10";
  }

  static const char* value(const ::behaviour::swarmstatereqRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe370fd289e7d098aULL;
  static const uint64_t static_value2 = 0xaf730ef08ac3ee10ULL;
};

template<class ContainerAllocator>
struct DataType< ::behaviour::swarmstatereqRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behaviour/swarmstatereqRequest";
  }

  static const char* value(const ::behaviour::swarmstatereqRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behaviour::swarmstatereqRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 pass\n"
;
  }

  static const char* value(const ::behaviour::swarmstatereqRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behaviour::swarmstatereqRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pass);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct swarmstatereqRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behaviour::swarmstatereqRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behaviour::swarmstatereqRequest_<ContainerAllocator>& v)
  {
    s << indent << "pass: ";
    Printer<int8_t>::stream(s, indent + "  ", v.pass);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOUR_MESSAGE_SWARMSTATEREQREQUEST_H
