// Generated by gencpp from file behaviour/target.msg
// DO NOT EDIT!


#ifndef BEHAVIOUR_MESSAGE_TARGET_H
#define BEHAVIOUR_MESSAGE_TARGET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace behaviour
{
template <class ContainerAllocator>
struct target_
{
  typedef target_<ContainerAllocator> Type;

  target_()
    : header()
    , id(0.0)
    , detectorid(0)
    , detectortype(0)
    , messagetime(0.0)
    , lat(0.0)
    , lon(0.0)
    , alt(0.0)
    , clas(0)
    , confidence(0.0)  {
    }
  target_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0.0)
    , detectorid(0)
    , detectortype(0)
    , messagetime(0.0)
    , lat(0.0)
    , lon(0.0)
    , alt(0.0)
    , clas(0)
    , confidence(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _id_type;
  _id_type id;

   typedef int8_t _detectorid_type;
  _detectorid_type detectorid;

   typedef int8_t _detectortype_type;
  _detectortype_type detectortype;

   typedef double _messagetime_type;
  _messagetime_type messagetime;

   typedef double _lat_type;
  _lat_type lat;

   typedef double _lon_type;
  _lon_type lon;

   typedef float _alt_type;
  _alt_type alt;

   typedef int8_t _clas_type;
  _clas_type clas;

   typedef float _confidence_type;
  _confidence_type confidence;





  typedef boost::shared_ptr< ::behaviour::target_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behaviour::target_<ContainerAllocator> const> ConstPtr;

}; // struct target_

typedef ::behaviour::target_<std::allocator<void> > target;

typedef boost::shared_ptr< ::behaviour::target > targetPtr;
typedef boost::shared_ptr< ::behaviour::target const> targetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behaviour::target_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behaviour::target_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behaviour::target_<ContainerAllocator1> & lhs, const ::behaviour::target_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.id == rhs.id &&
    lhs.detectorid == rhs.detectorid &&
    lhs.detectortype == rhs.detectortype &&
    lhs.messagetime == rhs.messagetime &&
    lhs.lat == rhs.lat &&
    lhs.lon == rhs.lon &&
    lhs.alt == rhs.alt &&
    lhs.clas == rhs.clas &&
    lhs.confidence == rhs.confidence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behaviour::target_<ContainerAllocator1> & lhs, const ::behaviour::target_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behaviour

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::behaviour::target_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behaviour::target_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour::target_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour::target_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour::target_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour::target_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behaviour::target_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a14509c50e32bd3f512cb2569673bbc";
  }

  static const char* value(const ::behaviour::target_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a14509c50e32bd3ULL;
  static const uint64_t static_value2 = 0xf512cb2569673bbcULL;
};

template<class ContainerAllocator>
struct DataType< ::behaviour::target_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behaviour/target";
  }

  static const char* value(const ::behaviour::target_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behaviour::target_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 id\n"
"int8 detectorid\n"
"int8 detectortype\n"
"float64 messagetime\n"
"float64 lat\n"
"float64 lon\n"
"float32 alt\n"
"int8 clas\n"
"float32 confidence\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::behaviour::target_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behaviour::target_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.detectorid);
      stream.next(m.detectortype);
      stream.next(m.messagetime);
      stream.next(m.lat);
      stream.next(m.lon);
      stream.next(m.alt);
      stream.next(m.clas);
      stream.next(m.confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct target_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behaviour::target_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behaviour::target_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    Printer<double>::stream(s, indent + "  ", v.id);
    s << indent << "detectorid: ";
    Printer<int8_t>::stream(s, indent + "  ", v.detectorid);
    s << indent << "detectortype: ";
    Printer<int8_t>::stream(s, indent + "  ", v.detectortype);
    s << indent << "messagetime: ";
    Printer<double>::stream(s, indent + "  ", v.messagetime);
    s << indent << "lat: ";
    Printer<double>::stream(s, indent + "  ", v.lat);
    s << indent << "lon: ";
    Printer<double>::stream(s, indent + "  ", v.lon);
    s << indent << "alt: ";
    Printer<float>::stream(s, indent + "  ", v.alt);
    s << indent << "clas: ";
    Printer<int8_t>::stream(s, indent + "  ", v.clas);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOUR_MESSAGE_TARGET_H
