// Generated by gencpp from file behaviour/targetlist.msg
// DO NOT EDIT!


#ifndef BEHAVIOUR_MESSAGE_TARGETLIST_H
#define BEHAVIOUR_MESSAGE_TARGETLIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <behaviour/target.h>

namespace behaviour
{
template <class ContainerAllocator>
struct targetlist_
{
  typedef targetlist_<ContainerAllocator> Type;

  targetlist_()
    : header()
    , targets()  {
    }
  targetlist_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , targets(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::behaviour::target_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::behaviour::target_<ContainerAllocator> >::other >  _targets_type;
  _targets_type targets;





  typedef boost::shared_ptr< ::behaviour::targetlist_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behaviour::targetlist_<ContainerAllocator> const> ConstPtr;

}; // struct targetlist_

typedef ::behaviour::targetlist_<std::allocator<void> > targetlist;

typedef boost::shared_ptr< ::behaviour::targetlist > targetlistPtr;
typedef boost::shared_ptr< ::behaviour::targetlist const> targetlistConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behaviour::targetlist_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behaviour::targetlist_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behaviour::targetlist_<ContainerAllocator1> & lhs, const ::behaviour::targetlist_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.targets == rhs.targets;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behaviour::targetlist_<ContainerAllocator1> & lhs, const ::behaviour::targetlist_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behaviour

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::behaviour::targetlist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behaviour::targetlist_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour::targetlist_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour::targetlist_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour::targetlist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour::targetlist_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behaviour::targetlist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7397c01d017cf1d6405f3f3b22dc1d5a";
  }

  static const char* value(const ::behaviour::targetlist_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7397c01d017cf1d6ULL;
  static const uint64_t static_value2 = 0x405f3f3b22dc1d5aULL;
};

template<class ContainerAllocator>
struct DataType< ::behaviour::targetlist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behaviour/targetlist";
  }

  static const char* value(const ::behaviour::targetlist_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behaviour::targetlist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"target[] targets\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: behaviour/target\n"
"Header header\n"
"float64 id\n"
"int8 detectorid\n"
"int8 detectortype\n"
"float64 messagetime\n"
"float64 lat\n"
"float64 lon\n"
"float32 alt\n"
"int8 clas\n"
"float32 confidence\n"
;
  }

  static const char* value(const ::behaviour::targetlist_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behaviour::targetlist_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.targets);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct targetlist_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behaviour::targetlist_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behaviour::targetlist_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "targets[]" << std::endl;
    for (size_t i = 0; i < v.targets.size(); ++i)
    {
      s << indent << "  targets[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::behaviour::target_<ContainerAllocator> >::stream(s, indent + "    ", v.targets[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOUR_MESSAGE_TARGETLIST_H
