// Generated by gencpp from file behaviour/task.msg
// DO NOT EDIT!


#ifndef BEHAVIOUR_MESSAGE_TASK_H
#define BEHAVIOUR_MESSAGE_TASK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <behaviour/task_geometry.h>

namespace behaviour
{
template <class ContainerAllocator>
struct task_
{
  typedef task_<ContainerAllocator> Type;

  task_()
    : header()
    , task_id(0)
    , task_geometry()
    , allocated(0)
    , type(0)  {
    }
  task_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , task_id(0)
    , task_geometry(_alloc)
    , allocated(0)
    , type(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _task_id_type;
  _task_id_type task_id;

   typedef  ::behaviour::task_geometry_<ContainerAllocator>  _task_geometry_type;
  _task_geometry_type task_geometry;

   typedef int8_t _allocated_type;
  _allocated_type allocated;

   typedef int8_t _type_type;
  _type_type type;





  typedef boost::shared_ptr< ::behaviour::task_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behaviour::task_<ContainerAllocator> const> ConstPtr;

}; // struct task_

typedef ::behaviour::task_<std::allocator<void> > task;

typedef boost::shared_ptr< ::behaviour::task > taskPtr;
typedef boost::shared_ptr< ::behaviour::task const> taskConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behaviour::task_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behaviour::task_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behaviour::task_<ContainerAllocator1> & lhs, const ::behaviour::task_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.task_id == rhs.task_id &&
    lhs.task_geometry == rhs.task_geometry &&
    lhs.allocated == rhs.allocated &&
    lhs.type == rhs.type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behaviour::task_<ContainerAllocator1> & lhs, const ::behaviour::task_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behaviour

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::behaviour::task_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behaviour::task_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour::task_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour::task_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour::task_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour::task_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behaviour::task_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d31710c0e937328d90b6fc9fdf8068e";
  }

  static const char* value(const ::behaviour::task_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d31710c0e937328ULL;
  static const uint64_t static_value2 = 0xd90b6fc9fdf8068eULL;
};

template<class ContainerAllocator>
struct DataType< ::behaviour::task_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behaviour/task";
  }

  static const char* value(const ::behaviour::task_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behaviour::task_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int8 task_id\n"
"task_geometry task_geometry\n"
"int8 allocated\n"
"int8 type\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: behaviour/task_geometry\n"
"Header header\n"
"float64 lat\n"
"float64 lon\n"
"float32 alt\n"
;
  }

  static const char* value(const ::behaviour::task_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behaviour::task_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.task_id);
      stream.next(m.task_geometry);
      stream.next(m.allocated);
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct task_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behaviour::task_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behaviour::task_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "task_id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.task_id);
    s << indent << "task_geometry: ";
    s << std::endl;
    Printer< ::behaviour::task_geometry_<ContainerAllocator> >::stream(s, indent + "  ", v.task_geometry);
    s << indent << "allocated: ";
    Printer<int8_t>::stream(s, indent + "  ", v.allocated);
    s << indent << "type: ";
    Printer<int8_t>::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOUR_MESSAGE_TASK_H
