(cl:in-package behaviour-msg)
(cl:export '(HEADER-VAL
          HEADER
          POINTS-VAL
          POINTS
          LAT1-VAL
          LAT1
          LAT2-VAL
          LAT2
          LAT3-VAL
          LAT3
          LAT4-VAL
          LAT4
          LAT5-VAL
          LAT5
          LAT6-VAL
          LAT6
          LAT7-VAL
          LAT7
          LAT8-VAL
          LAT8
          LON1-VAL
          LON1
          LON2-VAL
          LON2
          LON3-VAL
          LON3
          LON4-VAL
          LON4
          LON5-VAL
          LON5
          LON6-VAL
          LON6
          LON7-VAL
          LON7
          LON8-VAL
          LON8
          ALT1-VAL
          ALT1
          ALT2-VAL
          ALT2
          ALT3-VAL
          ALT3
          ALT4-VAL
          ALT4
          ALT5-VAL
          ALT5
          ALT6-VAL
          ALT6
          ALT7-VAL
          ALT7
          ALT8-VAL
          ALT8
))