(cl:in-package behaviour-msg)
(cl:export '(HEADER-VAL
          HEADER
          POINTS-VAL
          POINTS
          LAT1-VAL
          LAT1
          LAT2-VAL
          LAT2
          LAT3-VAL
          LAT3
          LAT4-VAL
          LAT4
          LON1-VAL
          LON1
          LON2-VAL
          LON2
          LON3-VAL
          LON3
          LON4-VAL
          LON4
          ALT1-VAL
          ALT1
          ALT2-VAL
          ALT2
          ALT3-VAL
          ALT3
          ALT4-VAL
          ALT4
))