(cl:defpackage behaviour-srv
  (:use )
  (:export
   "AREAREQ"
   "<AREAREQ-REQUEST>"
   "AREAREQ-REQUEST"
   "<AREAREQ-RESPONSE>"
   "AREAREQ-RESPONSE"
   "CLEANREQ"
   "<CLEANREQ-REQUEST>"
   "CLEANREQ-REQUEST"
   "<CLEANREQ-RESPONSE>"
   "CLEANREQ-RESPONSE"
   "SWARMSTATEREQ"
   "<SWARMSTATEREQ-REQUEST>"
   "SWARMSTATEREQ-REQUEST"
   "<SWARMSTATEREQ-RESPONSE>"
   "SWARMSTATEREQ-RESPONSE"
   "SWARMSTATEREQRESPONSE"
   "<SWARMSTATEREQRESPONSE-REQUEST>"
   "SWARMSTATEREQRESPONSE-REQUEST"
   "<SWARMSTATEREQRESPONSE-RESPONSE>"
   "SWARMSTATEREQRESPONSE-RESPONSE"
  ))

